### PR TITLE
Update mods.json

### PR DESCRIPTION
**Pull request by coltondrg**
removed ddrc, stop stealing CykaDev's work.

### CODE REVIEW

**Comment by Niquolas** [comment]
There is no "stealing" involved here at all. The work is fully credited and I am not gaining anything from including it in DDMM. 

If there is a legitimate problem with the mod's inclusion, I suggest you ask the mod developer to contact me directly. I can't honour removal requests from people unaffiliated with the mod, unless it is causing a wider problem.

**Comment by coltondrg** [comment]
I have created this pull request at the developer's behest and am not unaffiliated. Inclusion of the mod on your launcher was not authorized and redistribution of the scripts and other original assets is unacceptable. The least you can do is provide a link to the actual CykaDev website and use the official download link to fetch the files from drg's servers.
CykaDev-Script-Distribution-Agreement

**Comment by Niquolas** [comment]
In this case, I'm perfectly happy to remove it.

**Comment by coltondrg** [comment]
Please make sure you also remove the assets from your Google App Engine mirror when convenient. Thank you.

**Comment by Niquolas** [comment]
I have already removed the hosted assets. You can verify this yourself if you want by visiting the link that was removed.

**Pull request closed without merging**
